version: "2"
services:

  #PHP Service
  phpa:
    container_name: phpa
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/laravel
    networks:
      - app-network

  #Nginx Service
  webserva:
    container_name: webserv
    image: nginx:latest
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9081:80"
      - "4431:443"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/:/var/log/nginx/
    networks:
      - app-network

  #MySQL Service
  dba:
    container_name: dba
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
