version: "2"
services:

#  www:
#    container_name: www
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/nginx/log/:/var/log/nginx/
#    depends_on:
#      - frontend
#      - backend
#    networks:
#      - app-network



  #PHP Service
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/laravel
    networks:
      - app-network

#  frontend:
#    container_name: frontend
#    build:
#      context: .
#      dockerfile: Dockerfile-frontend
#    networks:
#      - app-network
#    image: node:alpine
#    working_dir: /home/node/app
#    volumes:
#      - ./backend/resources/js:/home/node/app
#    environment:
#      NODE_ENV: development
#    command: "npm run serve"


  #Nginx Service
  webserva:
    container_name: webserv
    image: nginx:latest
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9081:80"
      - "4431:443"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/:/var/log/nginx/
    networks:
      - app-network

  #MySQL Service
  dba:
    container_name: dba
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: torrent
      MYSQL_ROOT_PASSWORD: qt67uy
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
